baseURL = 'https://korrektsiya-zreniya.net'
title = 'ЛАЗЕРНАЯ КОРРЕКЦИЯ ЗРЕНИЯ: ВСЯ ПРАВДА'
languageCode = 'ru'
languageName = 'ru'
defaultContentLanguage = "ru"
enableGitInfo = false
theme = "mainroad"

[services]
  [services.googleAnalytics]
    id = 'G-N1FNTQ7NCM'

[taxonomies]
	category = "categories"
	tag = "tags"

[slug]
  transliterations = "russian"

[permalinks]
  novosti = "/:slug/"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[params]
  favicon="favicon.ico"

[Params]
  description = "Скрытые риски и побочные эффекты. Реальные отзывы и осложнения спустя много лет. Офтальмологи против - от лазерной коррекции можно ослепнуть. Почему не стоит делать операцию на глаза. Вся правда о лазерной коррекции зрения."
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  mainSections = []
  post_meta = ["date"] 
  dateformat = "2006-01-02" # Change the format of dates
  readmore = true
  pager = true
  favicon="favicon.ico"
  googleFontsLink = false
  


[Params.style.vars]
  highlightColor = "#e22d30" # Override highlight color


[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "taglist", "recent"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  #categories_counter = true # Enable counter for each category in "Categories" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget


[Params.thumbnail]
  visibility = ["list"] # Control thumbnail visibility

[Params.widgets.social]
  cached = true # activate cache if true
  twitter = "username"
  telegram = "lasik_chat"


[[Params.widgets.social.custom]]
  title = "Чат пациентов"
  url = "https://t.me/lasik_chat"
  #icon = "youtube.svg" # Optional. Path relative to "layouts/partials"
  rel = "noopener noreferrer" # Set to false to remove the rel attribute

[Params.logo]
  image = "/images/eye-icon.png" # Logo image. Path relative to "static"
  title = "ЛАЗЕРНАЯ КОРРЕКЦИЯ ЗРЕНИЯ: ВСЯ ПРАВДА" # Logo title, otherwise will use site title
  subtitle = "Независимый социальный проект" # Logo subtitle

[menu]
[[menu.main]]
name = "Главная"
url = "/"
weight = 10

[[menu.main]]
name = "Новости"
url = "/novosti/"
identifier = "novosti"
weight = 20

[[menu.main]]
name = "Риски и последствия"
url = "/riski-i-posledstviya/"
identifier = "riski-i-posledstviya"
weight = 30

[[menu.main]]
name = "Побочные эффекты"
url = "/pobochnye-effekty/"
identifier = "pobochnye-effekty"
weight = 40

[[menu.main]]
name = "Осложнения"
url = "/oslozhneniya/"
identifier = "oslozhneniya"
weight = 50

[[menu.main]]
name = "Отзывы"
url = "/otzyvy/"
weight = 60

[[menu.main]]
name = "Судебные дела"
url = "/sudebnye-dela/"
weight = 70

[[menu.footer]]
name = "Благодарности и идея"
url = "http://lasikcomplications.com"
weight = 100

[imaging]
  anchor = 'Smart'
  quality = 75
  [imaging.exif]
    disableDate = true
    disableLatLong = true
    excludeFields = ''
    includeFields = ''
